# Generated by Django 2.0.4 on 2019-01-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
    ]
